# -*- coding: utf-8 -*-
"""resume-matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5xGW1GtIG3eRttISwUmsvZBuN6oG35K
"""

import math

def normalize_and_deduplicate_skills(raw_skills):
    """
    Normalize and deduplicate skills from a raw string.

    Args:
        raw_skills (str): Raw skills string.

    Returns:
        list: List of normalized and deduplicated skills.
    """
    # Split raw skills on commas
    skills = [skill.strip() for skill in raw_skills.split(',')]

    # Create a dictionary to store the normalized skills
    normalized_skills = {}

    # Iterate over each skill
    for skill in skills:
        # Lowercase the skill
        skill = skill.lower()

        # Check if the skill is a multi-word phrase
        for key in SKILL_ALIASES:
            if key in skill:
                # If the skill is a multi-word phrase, use the alias
                normalized_skill = SKILL_ALIASES[key]
                if normalized_skill not in normalized_skills:
                    normalized_skills[normalized_skill] = True
                break
        else:
            # If the skill is not a multi-word phrase, check if it's in the SKILL_ALIASES dictionary
            if skill in SKILL_ALIASES:
                # If the skill is in the dictionary, use the alias
                normalized_skill = SKILL_ALIASES[skill]
                if normalized_skill not in normalized_skills:
                    normalized_skills[normalized_skill] = True

    # Return the list of normalized and deduplicated skills
    return list(normalized_skills.keys())

# Test the function
raw_skills = 'Pyhton, MachineLearning, SQL, pandas, numpy, Deep-learning'
print(normalize_and_deduplicate_skills(raw_skills))

# Define the normalized skills for each resume
normalized_skills = {
    'Arjun Sharma': ['python', 'machine_learning', 'sql', 'pandas', 'numpy', 'deep_learning'],
    'Priya Nair': ['javascript', 'react', 'nodejs', 'mongodb', 'rest_api', 'html_css'],
    'Rahul Gupta': ['java', 'spring_boot', 'mysql', 'microservices', 'docker', 'kubernetes'],
    'Sneha Patel': ['python', 'tensorflow', 'keras', 'nlp', 'bert', 'data_visualization'],
    'Vikram Singh': ['cpp', 'algorithms', 'data_structures', 'competitive_programming', 'python'],
    'Ananya Krishnan': ['javascript', 'vue', 'python', 'flask', 'postgresql', 'aws', 'ci_cd'],
    'Karan Mehta': ['python', 'machine_learning', 'xgboost', 'feature_engineering', 'sql', 'data_visualization'],
    'Deepika Rao': ['java', 'android', 'kotlin', 'firebase', 'rest_api', 'ui_ux', 'figma'],
    'Aditya Kumar': ['react', 'typescript', 'graphql', 'redux', 'tailwind', 'nodejs', 'jest'],
    'Meera Iyer': ['python', 'r', 'statistics', 'machine_learning', 'regression', 'clustering', 'data_visualization']
}

# Define the vocabulary
vocabulary = sorted(set([skill for skills in normalized_skills.values() for skill in skills]))

# Compute document frequency (df) counts
df_counts = {skill: 0 for skill in vocabulary}
for skills in normalized_skills.values():
    for skill in set(skills):
        df_counts[skill] += 1

# Compute IDF values
idf_values = {skill: math.log(10 / count) for skill, count in df_counts.items()}

# Compute TF-IDF vectors
tfidf_vectors = {}
for name, skills in normalized_skills.items():
    tfidf_vector = [0.0] * len(vocabulary)
    for i, skill in enumerate(vocabulary):
        if skill in skills:
            tfidf_vector[i] = (1 / len(skills)) * idf_values[skill]
    tfidf_vectors[name] = tfidf_vector

# Define the job descriptions (required + preferred skills included)
job_descriptions = {
    'JD-1': 'Python, Machine Learning, Deep Learning, TensorFlow, PyTorch, SQL, Data Visualization, NLP, BERT, Feature Engineering, Statistics',
    'JD-2': 'Java, Spring Boot, MySQL, PostgreSQL, Microservices, Docker, Kubernetes, REST API, CI/CD, Redis',
    'JD-3': 'JavaScript, React, Vue, TypeScript, REST API, HTML/CSS, Node.js, GraphQL, Redux, Jest, AWS'
}

# Define the SKILL_ALIASES dictionary
SKILL_ALIASES = {
# Languages
"python": "python",
"pyhton": "python",
"java": "java",
"javascript": "javascript",
"javascrpit": "javascript",
"js": "javascript",
"typescript": "typescript",
"typescrpit": "typescript",
"c++": "cpp",
"cpp": "cpp",
"r": "r",
"kotlin": "kotlin",
# ML / Data
"machinelearning": "machine_learning",
"machine learning": "machine_learning",
"ml": "machine_learning",
"sklearn": "machine_learning",
"deeplearning": "deep_learning",
"deep learning": "deep_learning",
"deep-learning": "deep_learning",
"tensorflow": "tensorflow",
"pytorch": "pytorch",
"keras": "keras",
"nlp": "nlp",
"bert": "bert",
"xgboost": "xgboost",
"feature engineering": "feature_engineering",
"statistics": "statistics",
"stats": "statistics",
"regression": "regression",
"clustering": "clustering",
"data-viz": "data_visualization",
"data visualization": "data_visualization",
"data viz": "data_visualization",
"matplotlib": "data_visualization",
"tableau": "data_visualization",
"power-bi": "data_visualization",
"power bi": "data_visualization",
"powerbi": "data_visualization",
"pandas": "pandas",
"numpy": "numpy",
# Web — Frontend
"react": "react",
"reacts": "react",
"reactjs": "react",
"vue": "vue",
"vue.js": "vue",
"vuejs": "vue",
"redux": "redux",
"tailwind": "tailwind",
"html/css": "html_css",
"html css": "html_css",
"html": "html_css",
"css": "html_css",
"jest": "jest",
"graphql": "graphql",
# Web — Backend
"node.js": "nodejs",
"nodejs": "nodejs",
"node js": "nodejs",
"flask": "flask",
"spring boot": "spring_boot",
"springboot": "spring_boot",
"rest api": "rest_api",
"rest": "rest_api",
"restapi": "rest_api",
"microservices": "microservices",
# Databases
"sql": "sql",
"mysql": "mysql",
"mysq": "mysql",
"postgresql": "postgresql",
"postgres": "postgresql",
"mongodb": "mongodb",
"redis": "redis",
# DevOps / Cloud
"docker": "docker",
"kubernetes": "kubernetes",
"kubernates": "kubernetes",
"k8s": "kubernetes",
"ci/cd": "ci_cd",
"cicd": "ci_cd",
"ci cd": "ci_cd",
"aws": "aws",
# Mobile
"android": "android",
"firebase": "firebase",
# CS Fundamentals
"algorithms": "algorithms",
"algoritms": "algorithms",
"data structure": "data_structures",
"data structures": "data_structures",
"competitive programming": "competitive_programming",
# Design
"ui/ux": "ui_ux",
"ui ux": "ui_ux",
"figma": "figma",
}

# Sort compound phrases longest-first for greedy matching
compound_phrases = sorted(
    [key for key in SKILL_ALIASES if " " in key or "/" in key or "-" in key],
    key=lambda phrase: -len(phrase)
)

# Normalize the job descriptions
normalized_job_descriptions = {}
for jd_name, description in job_descriptions.items():
    tokens = [skill.strip() for skill in description.lower().split(',')]
    normalized_skills_list = []
    seen = set()
    for token in tokens:
        matched = None
        for phrase in compound_phrases:
            if phrase in token:
                matched = SKILL_ALIASES[phrase]
                break
        if not matched:
            matched = SKILL_ALIASES.get(token)
        if matched and matched not in seen:
            seen.add(matched)
            normalized_skills_list.append(matched)
    normalized_job_descriptions[jd_name] = normalized_skills_list

# Compute binary vectors for job descriptions
binary_vectors = {}
for jd_name, skills in normalized_job_descriptions.items():
    binary_vector = [1.0 if skill in skills else 0.0 for skill in vocabulary]
    binary_vectors[jd_name] = binary_vector

# Compute cosine similarity
cosine_similarities = {}
for name, tfidf_vector in tfidf_vectors.items():
    cosine_similarities[name] = {}
    for jd_name, binary_vector in binary_vectors.items():
        dot_product = sum(a * b for a, b in zip(tfidf_vector, binary_vector))
        magnitude_a = math.sqrt(sum(a ** 2 for a in tfidf_vector))
        magnitude_b = math.sqrt(sum(b ** 2 for b in binary_vector))
        if magnitude_a * magnitude_b != 0:
            cosine_similarities[name][jd_name] = dot_product / (magnitude_a * magnitude_b)
        else:
            cosine_similarities[name][jd_name] = 0.0

# Output Top 3 candidates per JD
for jd_name in job_descriptions:
    sorted_candidates = sorted(
        cosine_similarities.items(),
        key=lambda x: (-x[1][jd_name], x[0])
    )
    print(f"{jd_name}:")
    for candidate, similarities in sorted_candidates[:3]:
        print(f"  {candidate}({similarities[jd_name]:.2f})")
    print()

